########
#Configuration file for pulsar analysis using ptiming_ana
#######

###############################################################
##################### CPHASE PARAMS ###########################
###############################################################
cphase_setting:
   tel: lst 
   use_interpolation: True


###############################################################
##################### GENERAL PARAMS ##########################
###############################################################

# -------- FILE DIRECTORY -----------
ephem_dir: '/home/alvaro.mas/software/Pulsar_analysis/data/all.gro'
pulsar_file_dir: '/fefs/aswg/workspace/alvaro.mas/data/real/Crab/v0.9_newmc/src_dependent/DL3_pulsar_sys_eff_6nodes/eff_0.7/'
results_output_directory: '/fefs/aswg/workspace/alvaro.mas/data/real/Crab/v0.9_newmc/src_dependent/bridge/'
DL4_directory: '/fefs/aswg/workspace/alvaro.mas/data/real/Crab/v0.9_newmc/src_dependent/bridge_E/'

target:
  name: Crab
  ra: 83.633
  dec: 22.01


# -------- REGIONS ---------

phase_regions:
  Bkg: [0.52,0.87]
  P1: [0,0.026,0.983,1]
  P2: [0.377,0.422]
  P1+P2: [0,0.026,0.377,0.422, 0.983,1]
  P3: [0.08,0.24]
  
  

###############################################################
##################### PHASEOGRAM TOOLS ########################
###############################################################


flags:
  src_dependent: False
  DL2_format: False
  fits_format: False

cuts:
  energy_dependent_theta: False
  filter_data: True
  include_DL2_extra_cuts: False
  zd_range: [0,50]
  max_rad: 0.32
  extra_cuts:
    energy_dependent: False
    theta: 0.2
    alpha:  15
    intensity: 50
    gammaness: 0.5
    energy_binning: [0,0.02,1000]



#-------- BINNING--------------

phase_binning:
  xmin: 0
  xmax: 1
  nbins: 50
  custom_binning: False
  binning: [0,0.1,0.2]


time_binning:
   run_time_analysis: True
   units: h
   tint: 200


energy_binning:
   run_energy_analysis: True
   do_diff: True #Set to True if want to calculate statistics for data in each energy bin (i.e 50 GeV < E < 80 GeV)
   do_integral: True # Set to True if want to calculate statistics for data above each energy edge (i.e E>50 GeV)
   units: GeV
   emin: 20
   emax: 700
   nbins: 8



# --------- PHASEOGRAM MODEL-----------
fitting:
   run_fitting: True
   model: dgaussian   # Choose among dgaussian, asym_dgaussian, lorentzian
   binned: False


results:
   save_results: False
   output_directory: '/fefs/aswg/workspace/alvaro.mas/data/real/Crab/v0.9_newmc/src_dependent/phaseogram/'


###############################################################
##################### SPECTRAL TOOLS ##########################
###############################################################


reader:
  energy_dependent_theta: False
  max_rad: 0.2
  zd_range: [0,50]
  use_DL4: False
  save_DL4: True

energy_geometry:
  real:
    emin: 0.003
    emax: 50
    units: 'TeV'
    nbinning: 100
  reco:
    emin: 0.01
    emax: 10
    units: 'TeV'
    nbinning: 40
    
analysis_extra_settings:
  stacked: True
  use_safe_mask: False


spectral_fitting:
  emin: 20
  emax: 200
  units: 'GeV'
  model: 'PowerLaw'
    

spectral_points:
  emin: 20
  emax: 200
  units: 'GeV'
  number_points: 5
  min_ts: 1.5
  

  
