name: pulsar-lst1
channels:
  - default
dependencies:
  - python=3.7
  - pip
  - astropy
  - conda-forge::nbsphinx
  - conda-forge::ctapipe=0.12
  - conda-forge::gammapy=0.19.0
  - cython
  - graphviz
  - h5py
  - iminuit>=2
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - matplotlib
  - numba
  - numpy>=1.17
  - numpydoc
  - pandas
  - pre-commit
  - psutil
  - pyyaml
  - scipy
  - setuptools
  - sphinx=4.2
  - sphinx-automodapi
  - sphinx_rtd_theme
  - tqdm
  - traitlets
  - vitables
  - wheel
  - xz
  - zlib
  - zstandard
  - conda-forge::eventio>=1.5.0
  - pip:
      - lstchain~=0.9.6
      - pint-pulsar
